services:
    - name: product-service
      entrypoint: http://product-service:5001/
      inject_token_in_swagger: True
    - name: delivery-service
      entrypoint: http://delivery-service:5002/
      inject_token_in_swagger: True
    - name: user-service
      entrypoint: http://user-service:5003/
      inject_token_in_swagger: True
    - name: feedback-service
      entrypoint: http://feedback-service:5004/
      inject_token_in_swagger: True
    - name: favorite-service
      entrypoint: http://favorite-service:5005/
      inject_token_in_swagger: True
    - name: basket-service
      entrypoint: http://basket-service:5007/
      inject_token_in_swagger: True
model: |
    [request_definition]
    r = sub, obj, act
    
    [policy_definition]
    p = sub_rule, obj, act
    
    [policy_effect]
    e = some(where (p.eft == allow))
    
    [matchers]
    m = eval(p.sub_rule) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
policies:
      #group_id
      #1 - Покупатель услуг
      #2 - Админ

      #Покупатель услуг
    - service: product-service
      rule: r.sub.group_id == 1
      resource: /products*
      methods: GET
    - service: delivery-service
      rule: r.sub.group_id == 1
      resource: /deliveries*
      methods: GET
    - service: user-service
      rule: r.sub.group_id == 1
      resource: /users/*
      methods: GET
    - service: basket-service
      rule: r.sub.group_id == 1
      resource: /baskets*
      methods: (GET)|(POST)|(PUT)|(DELETE)
    - service: basket-service
      rule: r.sub.group_id == 1
      resource: /uploads*
      methods: (GET)|(POST)|(PUT)|(DELETE) 

      #Админ
    - service: favorite-service
      rule: r.sub.group_id == 2
      resource: /favorites*
      methods: (GET)|(POST)|(PUT)|(DELETE)
    - service: delivery-service
      rule: r.sub.group_id == 2
      resource: /deliveries*
      methods: (GET)|(POST)|(PUT)|(DELETE)
    - service: user-service
      rule: r.sub.group_id == 2
      resource: /users/*
      methods: (GET)|(POST)|(PUT)|(DELETE)
    - service: user-service
      rule: r.sub.group_id == 2
      resource: /groups*
      methods: (GET)|(POST)|(PUT)|(DELETE)
    - service: feedback-service
      rule: r.sub.group_id == 2
      resource: /feedbacks*
      methods: (GET)|(POST)|(PUT)|(DELETE)
    - service: basket-service
      rule: r.sub.group_id == 2
      resource: /baskets*
      methods: (GET)|(POST)|(PUT)|(DELETE)
    - service: basket-service
      rule: r.sub.group_id == 2
      resource: /uploads*
      methods: (GET)|(POST)|(PUT)|(DELETE)
    - service: product-service
      rule: r.sub.group_id == 2
      resource: /products*
      methods: (GET)|(POST)|(PUT)|(DELETE)

      #Общее
    - service: user-service
      resource: /auth/*
      methods: POST
      white_list: true