version: "2.0"
services:
  postgresql:
    image: postgis/postgis:latest
    container_name: postgis
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 120s
      retries: 5
      start_period: 30s

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3      

  mongo:
    image: mongo:7.0
    volumes:
      - mongo-data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mongo
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  tests:
    build:
      context: ../tests
      dockerfile: ./Dockerfile
    depends_on:
      - feedback-service
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
      FEEDBACK_SERVICE_ENTRYPOINT: ${FEEDBACK_SERVICE_ENTRYPOINT}   

  basket-service:
    build:
      context: ../services/basket-service
      dockerfile: ./Dockerfile
    ports:
      - "5007:5007"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
      PRODUCT_ENTRYPOINT: ${PRODUCT_ENTRYPOINT}
      RABBITMQ_DSN: ${RABBITMQ_DSN}
      QUEUE_NAME: ${QUEUE_NAME_NOTIFICATION}
      EXCHANGE_NAME: ${EXCHANGE_NAME_NOTIFICATION}

  notification-service:
    build:
      context: ../services/notification-service
      dockerfile: ./Dockerfile
    ports:
      - "5006:5006"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      QUEUE_NAME: ${QUEUE_NAME_NOTIFICATION}
      RABBITMQ_DSN: ${RABBITMQ_DSN}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_LOGIN: ${EMAIL_LOGIN}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SERVER: ${SMTP_SERVER}

  feedback-service:
    build:
      context: ../services/feedback-service
      dockerfile: ./Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - mongo
    environment:
      MONGO_DSN: ${MONGO_DSN}

  policy-enforcement-service:
    build:
      context: ../services/policy-enforcement-service
      dockerfile: ./Dockerfile
    ports:
      - "5100:5100"
    volumes:
      - policy-enforcement-data:/mnt/
    environment:
      JWT_SECRET: ${JWT_SECRET}
      POLICIES_CONFIG_PATH: ${POLICIES_CONFIG_PATH}

  product-service:
    build:
      context: ../services/product-service
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}

  delivery-service:
    build:
      context: ../services/delivery-service
      dockerfile: ./Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}

  user-service:
    build:
      context: ../services/user-service
      dockerfile: ./Dockerfile
    restart: unless-stopped    
    ports:
      - "5003:5003"
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - user-service-data:/mnt/
    environment:
      POSTGRES_DSN: ${POSTGRES_DB_ASYNC_DSN}
      JWT_SECRET: ${JWT_SECRET}
      RESET_PASSWORD_TOKEN_SECRET: ${RESET_PASSWORD_TOKEN_SECRET}
      VERIFICATION_TOKEN_SECRET: ${VERIFICATION_TOKEN_SECRET}
      DEFAULT_GROUPS_CONFIG_PATH: ${DEFAULT_GROUPS_CONFIG_PATH}


volumes:
  postgres_data:
  mongo-data:
  policy-enforcement-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./policy-enforcement-data
  user-service-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./user-service