version: '1.0'
services:
  postgresql:
    image: postgres:16.0  # Используйте версию PostgreSQL 16.0
    container_name: postgresql
    environment:
      POSTGRES_DB: "postgres"  # Имя вашей базы данных
      POSTGRES_USER: "postgres"    # Имя пользователя базы данных
      POSTGRES_PASSWORD: "1023"  # Пароль пользователя базы данных
      PGDATA: /var/lib/postgresql/data/db-files/
    ports:
      - 5432:5432  # Маппинг портов (локальный порт: порт в контейнере)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Монтирование тома для сохранения данных

  product-service:
    image: product-service:1.0
    ports:
      - "5001:5001"
    environment:
      PG_DSN: "postgresql://postgres:1023@postgresql:5432/postgres"

volumes:
  postgres_data: