version: '1.0'
services:
  postgresql:
    image: postgis/postgis:latest
    container_name: postgis
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1023
    ports:
      - 5432:5432  
    volumes:
      - /path/to/local/data:/var/lib/postgresql/data 

  product-service:
    image: product-service:1.0
    ports:
      - "5001:5001"
    environment:
      PG_DSN: ${POSTGRES_DSN}

  delivery-service:
    image: delivery-service:1.0
    ports:
      - "5002:5002"
    environment:
      PG_DSN: ${POSTGRES_DSN}


volumes:
  postgres_data: